# Keep this minimal Dependabot config as a security backstop.
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      # Security updates ignore this and are opened ad-hoc, but this is still a required option.
      interval: daily
    # Prevent PRs from opening except for security updates, as per https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
    open-pull-requests-limit: 0
