# We have authorized the GitHub application mergify. Read more about it at https://docs.mergify.com/examples/#dependabot.
pull_request_rules:
  - name: Auto-approve upgrades
    conditions:
      - or:
          - author=renovate[bot]
          - author=dependabot[bot]
      - -label=major-upgrade
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependency upgrade
  - name: Auto-merge upgrades
    conditions:
      - or:
          - and:
              - author=renovate[bot]
              - title~=update dependency
          - author=dependabot[bot]
      - -label=major-upgrade
    actions:
      merge:
        method: squash
